/* jshint ignore:start */

module.exports = {
    TOKEN_SECRET: process.env.TOKEN_SECRET || "tokenultrasecreto",
    FACEBOOK_SECRET: "7f75842e0bc23f1ace47e4dc63ecef24",
    EMAIL_PASSWORD: "babelpop",
    HTML_MSG1_EN: '<div class="readMsgBody">' + '<div id="bodyreadMessagePartBodyControl694f" class="ExternalClass MsgBodyContainer" data-link="class{:~tag.cssClasses(PlainText, IsContentFiltered)}">     <title>Babelpop: new password</title> <style>' +
                    '</style>  <table width="100%"> <tbody><tr> <td bgcolor="#fff" class="ecxbackground" align="center" style="padding:0px;"> <table class="ecxbackgroundtop" bgcolor="#13c1ac" style="max-width:600px;width:100%;height:60px;border-radius:30px 30px 0 0;"> <tbody><tr> <td></td> <td> <div style="padding:0;display:block;"> <table style="width:100%;"> <tbody><tr> <td width="5%"></td> <td align="left" width="50%"> Babelpop </td> <td width="5%"></td> <td align="right" width="40%">' +
                    '</a> <a style="text-decoration:none;" href="http://s3s-es3.net/fw19c3/2301667/904/821117243.html?p=7f96da41b7d954434831efc84a6f2461&amp;u=http://instagram.com/Babelpop" target="_blank"> <img class="ecximghidden" width="0" src="https://dub124.mail.live.com/Handlers/ImageProxy.mvc?bicild=&amp;canary=VIqH%2b%2ftXgZoYhptKk4cqfthO3h8BcRDp9D7f00RsP2c%3d0&amp;url=http%3a%2f%2fd22j03ecumputt.cloudfront.net%2fmailing%2fico_in1.png"> </a> <a style="text-decoration:none;" href="http://s3s-es3.net/fw19c3/2301667/904/821117243.html?p=5889091b585eac2849cd10057df66cc9&amp;u=https://www.youtube.com/user/BabelpopApp" target="_blank"> <img class="ecximghidden" width="0" src="https://dub124.mail.live.com/Handlers/ImageProxy.mvc?bicild=&amp;canary=VIqH%2b%2ftXgZoYhptKk4cqfthO3h8BcRDp9D7f00RsP2c%3d0&amp;url=http%3a%2f%2fd22j03ecumputt.cloudfront.net%2fmailing%2fico_yt1.png"> </a> </td> <td width="5%"></td> </tr> </tbody></table> </div> </td> <td></td> </tr> </tbody></table> <table bgcolor="#FFFFFF" style="border-right-style:solid;border-right-width:1px;border-right-color:#f1f0f0;border-left-style:solid;border-left-width:1px;border-left-color:#f1f0f0;max-width:600px;width:100%;" class="ecxdeviceWidth" align="center"> <tbody><tr> <td></td> <td align="center" style="display:block !important;clear:both !important;"> <div style="padding:15px;display:block;"> <table> <tbody><tr> <td align="center"> <font style="font-size:18px;color:#13c1ac;"> <br> <br> </font> <font style="font-size:16px;color:#717171;"> You have requested a new password for your Babelpops account. <br> <br> Your new password for Babelpop is <b>',
    HTML_MSG2_EN: '</b> <br> <br> </font> </td> </tr> </tbody></table> </div> </td> <td></td> </tr> </tbody></table> <table bgcolor="#fff" style="max-width:600px;width:100%;clear:both !important;"> <tbody><tr> <td></td> <td> <div style="padding:0;display:block;"> <table style="width:100%;"> <tbody><tr> <td align="center">  </td> </tr> </tbody></table> </div> </td> <td></td> </tr> </tbody></table> <table class="ecxbackgroundbottom" bgcolor="#f1f0f0" style="max-width:600px;border-radius:0 0 30px 30px;width:100%;height:60px;clear:both !important;"> <tbody><tr> <td></td> <td> <div style="padding:0;display:block;"> <table style="width:100%;"> <tbody><tr> <td align="center"> <p> <font style="font-size:13px;color:#666;"> Contact us via <a style="text-decoration:none;" href="mailto:babelpopteam@gmail.com">babelpopteam@gmail.com</a> | <a style="text-decoration:none;" href="http://s3s-es3.net/fw19c3/2301667/904/821117243.html?p=4a896c1a673d0202619b887a19760531&amp;u=http://www.babelpop.com/es?utm_source%3Dwm%26utm_campaign%3Dws%26utm_medium%3Dmail" target="_blank">www.babelpop.com</a> </font> </p> </td> </tr> </tbody></table> </div> </td> <td></td> </tr> </tbody></table> </td> </tr> </tbody></table>' + '</div>        </div>',
    HTML_MSG1_ES: '<div class="readMsgBody">' + '<div id="bodyreadMessagePartBodyControl694f" class="ExternalClass MsgBodyContainer" data-link="class{:~tag.cssClasses(PlainText, IsContentFiltered)}">     <title>Babelpop: nuevo password</title> <style>' +
                    '</style>  <table width="100%"> <tbody><tr> <td bgcolor="#fff" class="ecxbackground" align="center" style="padding:0px;"> <table class="ecxbackgroundtop" bgcolor="#13c1ac" style="max-width:600px;width:100%;height:60px;border-radius:30px 30px 0 0;"> <tbody><tr> <td></td> <td> <div style="padding:0;display:block;"> <table style="width:100%;"> <tbody><tr> <td width="5%"></td> <td align="left" width="50%"> Babelpop </td> <td width="5%"></td> <td align="right" width="40%">' +
                    '</a> <a style="text-decoration:none;" href="http://s3s-es3.net/fw19c3/2301667/904/821117243.html?p=7f96da41b7d954434831efc84a6f2461&amp;u=http://instagram.com/Babelpop" target="_blank"> <img class="ecximghidden" width="0" src="https://dub124.mail.live.com/Handlers/ImageProxy.mvc?bicild=&amp;canary=VIqH%2b%2ftXgZoYhptKk4cqfthO3h8BcRDp9D7f00RsP2c%3d0&amp;url=http%3a%2f%2fd22j03ecumputt.cloudfront.net%2fmailing%2fico_in1.png"> </a> <a style="text-decoration:none;" href="http://s3s-es3.net/fw19c3/2301667/904/821117243.html?p=5889091b585eac2849cd10057df66cc9&amp;u=https://www.youtube.com/user/BabelpopApp" target="_blank"> <img class="ecximghidden" width="0" src="https://dub124.mail.live.com/Handlers/ImageProxy.mvc?bicild=&amp;canary=VIqH%2b%2ftXgZoYhptKk4cqfthO3h8BcRDp9D7f00RsP2c%3d0&amp;url=http%3a%2f%2fd22j03ecumputt.cloudfront.net%2fmailing%2fico_yt1.png"> </a> </td> <td width="5%"></td> </tr> </tbody></table> </div> </td> <td></td> </tr> </tbody></table> <table bgcolor="#FFFFFF" style="border-right-style:solid;border-right-width:1px;border-right-color:#f1f0f0;border-left-style:solid;border-left-width:1px;border-left-color:#f1f0f0;max-width:600px;width:100%;" class="ecxdeviceWidth" align="center"> <tbody><tr> <td></td> <td align="center" style="display:block !important;clear:both !important;"> <div style="padding:15px;display:block;"> <table> <tbody><tr> <td align="center"> <font style="font-size:18px;color:#13c1ac;"> <br> <br> </font> <font style="font-size:16px;color:#717171;"> Has solicitado una nueva contraseña para tu cuenta de Babelpop. <br> <br> Tu nueva contraseña para Babelpop es <b>',
    HTML_MSG2_ES: '</b> <br> <br> </font> </td> </tr> </tbody></table> </div> </td> <td></td> </tr> </tbody></table> <table bgcolor="#fff" style="max-width:600px;width:100%;clear:both !important;"> <tbody><tr> <td></td> <td> <div style="padding:0;display:block;"> <table style="width:100%;"> <tbody><tr> <td align="center">  </td> </tr> </tbody></table> </div> </td> <td></td> </tr> </tbody></table> <table class="ecxbackgroundbottom" bgcolor="#f1f0f0" style="max-width:600px;border-radius:0 0 30px 30px;width:100%;height:60px;clear:both !important;"> <tbody><tr> <td></td> <td> <div style="padding:0;display:block;"> <table style="width:100%;"> <tbody><tr> <td align="center"> <p> <font style="font-size:13px;color:#666;"> ¿Dudas? Escríbenos a <a style="text-decoration:none;" href="mailto:babelpopteam@gmail.com">babelpopteam@gmail.com</a> | <a style="text-decoration:none;" href="http://s3s-es3.net/fw19c3/2301667/904/821117243.html?p=4a896c1a673d0202619b887a19760531&amp;u=http://www.babelpop.com/es?utm_source%3Dwm%26utm_campaign%3Dws%26utm_medium%3Dmail" target="_blank">www.babelpop.com</a> </font> </p> </td> </tr> </tbody></table> </div> </td> <td></td> </tr> </tbody></table> </td> </tr> </tbody></table>' + '</div>        </div>'
};